// Shared record form used by the datasheet and the Forms view.
// Builds type-aware inputs, validates through Engine and saves via Engine.
const RecordForm = {
    tableId: null,
    recordIndex: null,   // null => create new record
    onSave: null,        // optional callback after save

    open(tableId, recordIndex, onSave) {
        const table = Engine.getTable(tableId);
        if (!table) return;
        this.tableId = tableId;
        this.recordIndex = (recordIndex === undefined || recordIndex === null) ? null : recordIndex;
        this.onSave = onSave || null;

        const modal = document.getElementById('modal-record');
        const title = modal.querySelector('.modal-title');
        title.textContent = this.recordIndex !== null ? t('editRecordTitle') : t('addRecordTitle');

        const body = document.getElementById('record-form-fields');
        body.innerHTML = '';
        const record = this.recordIndex !== null ? table.records[this.recordIndex] : null;

        table.fields.forEach((field) => {
            const group = document.createElement('div');
            group.className = 'form-group';
            const label = document.createElement('label');
            label.setAttribute('for', 'rf-' + Utils.uid());
            label.textContent = field.name + (field.required ? ' *' : '') +
                (field.primaryKey ? ' (' + t('primaryKey') + ')' : '');
            group.appendChild(label);
            const input = this.buildInput(field, record ? record[field.name] : undefined);
            input.id = label.getAttribute('for');
            input.dataset.fieldName = field.name;
            group.appendChild(input);
            const err = document.createElement('p');
            err.className = 'field-error';
            err.hidden = true;
            group.appendChild(err);
            body.appendChild(group);
        });

        UI.openModal('modal-record');
    },

    buildInput(field, value) {
        let el;
        switch (field.type) {
            case 'auto_id':
                el = document.createElement('input');
                el.type = 'text';
                el.value = value !== undefined && value !== null && value !== '' ? String(value) : t('autoGenerated');
                el.disabled = true;
                break;
            case 'long_text':
                el = document.createElement('textarea');
                el.rows = 4;
                el.value = value || '';
                break;
            case 'boolean': {
                el = document.createElement('label');
                el.className = 'checkbox-control';
                const cb = document.createElement('input');
                cb.type = 'checkbox';
                cb.checked = value === true || value === 'true' || value === '1' || value === 1;
                const span = document.createElement('span');
                span.textContent = t('trueLabel');
                el.appendChild(cb);
                el.appendChild(span);
                el._isToggleWrapper = true;
                el.getValue = () => cb.checked;
                break;
            }
            case 'integer':
            case 'number':
                el = document.createElement('input');
                el.type = 'number';
                el.step = '1';
                el.value = value !== undefined ? value : '';
                break;
            case 'decimal':
                el = document.createElement('input');
                el.type = 'number';
                el.step = 'any';
                el.value = value !== undefined ? value : '';
                break;
            case 'date':
                el = document.createElement('input');
                el.type = 'date';
                el.value = value || '';
                break;
            case 'datetime':
                el = document.createElement('input');
                el.type = 'datetime-local';
                el.value = value ? String(value).replace(' ', 'T').slice(0, 16) : '';
                break;
            case 'email':
                el = document.createElement('input');
                el.type = 'email';
                el.value = value || '';
                break;
            case 'url':
                el = document.createElement('input');
                el.type = 'url';
                el.value = value || '';
                break;
            default:
                el = document.createElement('input');
                el.type = 'text';
                el.value = value === undefined || value === null ? '' : String(value);
        }
        if (!el.classList.contains('checkbox-control')) el.className = 'input-field';
        return el;
    },

    collect() {
        const table = Engine.getTable(this.tableId);
        const record = {};
        const groups = document.querySelectorAll('#record-form-fields .form-group');
        let firstError = null;
        table.fields.forEach((field, i) => {
            const group = groups[i];
            const input = group.querySelector('[data-field-name]');
            let value;
            if (field.type === 'boolean') {
                value = input.querySelector('input[type="checkbox"]').checked;
            } else if (field.type === 'auto_id') {
                value = '';
            } else if (field.type === 'datetime') {
                value = input.value ? input.value.replace('T', ' ') + ':00' : '';
            } else {
                value = input.value;
            }
            record[field.name] = value;
            const errEl = group.querySelector('.field-error');
            const errKey = Engine.validateFieldValue(field, value);
            if (errKey) {
                errEl.hidden = false;
                errEl.textContent = t(errKey, { field: field.name });
                if (!firstError) firstError = errKey;
            } else {
                errEl.hidden = true;
            }
        });
        return { record, hasFieldError: !!firstError };
    },

    submit() {
        const table = Engine.getTable(this.tableId);
        if (!table) return;
        const { record, hasFieldError } = this.collect();
        if (hasFieldError) return;
        try {
            if (this.recordIndex !== null) {
                Engine.updateRecord(this.tableId, this.recordIndex, record);
                UI.toast(t('toastRecordUpdated'), 'success');
            } else {
                Engine.addRecord(this.tableId, record);
                UI.toast(t('toastRecordAdded'), 'success');
            }
        } catch (e) {
            UI.handleError(e);
            return;
        }
        UI.closeModal();
        if (this.onSave) this.onSave();
    }
};
